name: Action CI

on:
  pull_request:
    branches: [master, main]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2

    - name: Verify action syntax 
      # The action should not publish any real changes, but should succeed.
      uses: './'
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        branch: '${{ github.event.pull_request.head.repo.default_branch }}'
        repository: '${{ github.event.pull_request.head.repo.full_name }}'
        test: true
